var clothes = [];
clothes.push("shirt");
clothes.push("T-shirt");
clothes.push("Tie");
clothes.push("trouser");
clothes.push("coat");
clothes.pop();
clothes.push("Vest");
console.log(clothes[2]);
var favcar = {};
favcar.color = "black";
favcar.covertible = "no";
console.log(favcar);